export const ADD_TO_WORKSPACE_SUCCESS = 'ADD_TO_WORKSPACE_SUCCESS';
export const REMOVE_FROM_WORKSPACE_SUCCESS = 'REMOVE_FROM_WORKSPACE_SUCCESS';
export const LOAD_WORKSPACE_SUCCESS = 'LOAD_WORKSPACE_SUCCESS';
export const CLEAR_WORKSPACE_SUCCESS = 'CLEAR_WORKSPACE_SUCCESS';
