export const GET_TEMPLATES_SUCCESS = 'GET_TEMPLATES_SUCCESS';
export const FLAG_GETTING_TEMPLATES = 'FLAG_GETTING_TEMPLATES';
export const FLAG_GETTING_TEMPLATE = 'FLAG_GETTING_TEMPLATE';
export const STAR_TEMPLATE_SUCCESS = 'STAR_TEMPLATE_SUCCESS';
export const STAR_TEMPLATE_ERROR = 'STAR_TEMPLATE_ERROR';
export const UNSTAR_TEMPLATE_SUCCESS = 'UNSTAR_TEMPLATE_SUCCESS';
export const UNSTAR_TEMPLATE_ERROR = 'UNSTAR_TEMPLATE_ERROR';
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS';
